name: 'Pact Can I Deploy Step'
description: 'Runs pact-broker can-i-deploy as a step'
inputs:
  pacticipant:
    description: 'Pacticipant to check'
    required: true
  environment:
    description: 'The environment you are deploying to'
    required: true
  version:
    description: 'The version (SHA) of the pacticipant'
    required: false
    default: ${{ github.sha }}
  pact_broker_url:
    required: true
  pact_broker_username:
    required: true
  pact_broker_password:
    required: true
  run_can_i_deploy:
    description: 'Whether to run the can-i-deploy check'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Create environment in Pact Broker
      shell: bash
      # Returns true if environment already exists (we don't need to create it again)
      run: |
        docker run --rm \
        -e PACT_BROKER_BASE_URL=${{ inputs.pact_broker_url }} \
        -e PACT_BROKER_USERNAME=${{ inputs.pact_broker_username }} \
        -e PACT_BROKER_PASSWORD=${{ inputs.pact_broker_password }} \
        pactfoundation/pact-cli:latest \
        broker create-environment --name ${{ inputs.environment }} || true
    - name: Pact Can I Deploy?
      if: ${{ inputs.run_can_i_deploy == 'true' }}
      shell: bash
      run: |
        docker run --rm \
          -e PACT_BROKER_BASE_URL=${{ inputs.pact_broker_url }} \
          -e PACT_BROKER_USERNAME=${{ inputs.pact_broker_username }} \
          -e PACT_BROKER_PASSWORD=${{ inputs.pact_broker_password }} \
          pactfoundation/pact-cli:latest \
          broker can-i-deploy \
          --pacticipant ${{ inputs.pacticipant }} \
          --version ${{ inputs.version }} \
          --to-environment ${{ inputs.environment }} \
          --retry-while-unknown 5 \
          --retry-interval 10