name: Publish image to ECR

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: 21
      java_distribution:
        required: false
        type: string
        default: temurin
      image_version:
        required: true
        type: string
      jar_subproject:
        required: false
        type: string
      image_scan:
        required: false
        type: string
        default: true
      image_scan_severity:
        required: false
        type: string
        default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      image_scan_skip_db_update:
        required: false
        type: string
        default: false
      image_scan_skip_java_db_update:
        required: false
        type: string
        default: false
      publish:
        required: false
        type: string
        default: true
      tag_with_latest:
        required: false
        type: boolean
        default: false
    secrets:
      gh_token:
        required: true
      ecr_region:
        required: true
      ecr_repository:
        required: true
      ecr_role_to_assume:
        required: true
      ecr_registry:
        required: false
      snyk_token:
        required: false
      root_certificate:
        required: false
      binding_directory:
        required: false
    outputs:
      published_image_version:
        description: "The version of the published image."
        value: ${{ jobs.ecr-publish-image.outputs.published_image_version }}

permissions:
  contents: read
  id-token: write

jobs:
  ecr-publish-image:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.gh_token }}
      ECR_REGISTRY: ${{ secrets.ecr_registry }}
      ROOT_CERTIFICATE: ${{ secrets.root_certificate }}

    outputs:
      published_image_version: ${{ steps.publish-image.outputs.published_image_version }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}

      - name: Configure aws credentials
        if: ${{ inputs.publish == 'true' }}
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.ecr_role_to_assume }}
          aws-region: ${{ secrets.ecr_region }}

      - name: Login ecr
        if: ${{ inputs.publish == 'true' && env.ECR_REGISTRY == '' }}
        uses: aws-actions/amazon-ecr-login@c962da2960ed15f492addc26fffa274485265950 # v2.0.2
        id: login-ecr

      - name: Login ecr in different registry
        if: ${{ inputs.publish == 'true' && env.ECR_REGISTRY != '' }}
        uses: aws-actions/amazon-ecr-login@c962da2960ed15f492addc26fffa274485265950 # v2.0.2
        with:
          registries: ${{ secrets.ecr_registry }}
        id: login-another-ecr
 
      - name: Configure certificate binding
        if: ${{ env.ROOT_CERTIFICATE != '' }}
        run: |
          if [ -z "${{ secrets.binding_directory }}" ]; then
            echo "A binding directory is required."
            exit 1
          fi
          mkdir -p ${{ secrets.binding_directory }}
          echo "${{ secrets.root_certificate }}" > ${{ secrets.binding_directory }}/root_cert.pem
          echo "ca-certificates" > ${{ secrets.binding_directory }}/type
          echo "created certificate binding"
          tree ${{ secrets.binding_directory }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Build image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry || steps.login-another-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ecr_repository }}
        run: |
          gradle_subproject=''
          if [ "${{ inputs.publish }}" != "true" ]; then
            # Set placeholder values when not publishing
            REGISTRY=registry
            REPOSITORY=repository
          fi
          if [[ -n "${{ inputs.jar_subproject }}" ]]; then
            gradle_subproject=":${{ inputs.jar_subproject }}:"
          fi
          image_name=${REGISTRY}/${REPOSITORY}:${{ inputs.image_version }}
          latest_image_name=${REGISTRY}/${REPOSITORY}:latest
          ./gradlew ${gradle_subproject}bootBuildImage \
            --imageName $image_name
          # Tag with latest as well if required
          if [[ "${{ inputs.tag_with_latest }}" == "true" ]]; then
            docker tag $image_name $latest_image_name
          fi
          echo "image_name=$image_name" >> $GITHUB_OUTPUT
          echo "latest_image_name=$latest_image_name" >> $GITHUB_OUTPUT
          echo "Image built with version: $image_name"

      - name: Scan image
        if: ${{ inputs.image_scan == 'true' }}
        uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          image: ${{ steps.build-image.outputs.image_name }}
          args: --severity-threshold=high

      - name: Upload image scan result to GitHub Code Scanning
        if: ${{ inputs.image_scan == 'true' }}
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          sarif_file: snyk.sarif

      - name: Publish image
        if: ${{ inputs.publish == 'true' }}
        id: publish-image
        run: |
          if [[ "${{ inputs.tag_with_latest }}" == "true" ]]; then
            docker push ${{ steps.build-image.outputs.image_name }}
            docker push ${{ steps.build-image.outputs.latest_image_name }}
            echo "published_image_version=${{ inputs.image_version }}" >> $GITHUB_OUTPUT
            echo "Image published to ECR with version: \`${{ inputs.image_version }}\` and tagged as \`latest\`" >> $GITHUB_STEP_SUMMARY
            echo "Published image version: ${{ inputs.image_version }} (also tagged as latest)"
          else
            docker push ${{ steps.build-image.outputs.image_name }}
            echo "published_image_version=${{ inputs.image_version }}" >> $GITHUB_OUTPUT
            echo "Image published to ECR with version: \`${{ inputs.image_version }}\`" >> $GITHUB_STEP_SUMMARY
            echo "Published image version: ${{ inputs.image_version }}"
          fi
